# Generated by Django 3.0 on 2019-12-12 09:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mechanical',
            new_name='python',
        ),
        migrations.RemoveField(
            model_name='electrical',
            name='author',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='author',
        ),
        migrations.DeleteModel(
            name='Computer',
        ),
        migrations.DeleteModel(
            name='Electrical',
        ),
        migrations.DeleteModel(
            name='Electronics',
        ),
    ]
