# Generated by Django 3.0 on 2019-12-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20191212_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='python',
            name='text',
            field=models.TextField(default=True),
        ),
    ]
